swagger: 2.0
info:
  version: 0.1.4
  title: App Store Receipt Validation
host: api.example.com
basePath: /0.1
schemes:
  - http
  - https
paths:
  /sandbox:
    get:
      summary: Validate a test receipt against the App Store sandbox.
      parameters:
        - in: query
          name: receipt
          type: string
          required: true
          description: Base 64 encoded app receipt data.
        - in: query
          name: secret
          type: string
          required: false
          description: Only used for receipts that contain auto-renewable subscriptions. Your app’s shared secret (a hexadecimal string).
        - in: query
          name: exclude
          type: string
          required: false
          description: Only used for iOS7 style app receipts that contain auto-renewable or non-renewing subscriptions. If value is true, response includes only the latest renewal transaction for any subscriptions.
      responses:
        200:
          description: OK
        400:
          description: No receipt data.
  /production:
      get:
        summary: Validate a production receipt against the App Store.
        parameters:
          - in: query
            name: receipt
            type: string
            required: true
            description: Base 64 encoded app receipt data.
          - in: query
            name: secret
            type: string
            required: false
            description: Only used for receipts that contain auto-renewable subscriptions. Your app’s shared secret (a hexadecimal string).
          - in: query
            name: exclude
            type: string
            required: false
            description: Only used for iOS7 style app receipts that contain auto-renewable or non-renewing subscriptions. If value is true, response includes only the latest renewal transaction for any subscriptions.
        responses:
          200:
            description: OK
          400:
            description: No receipt data.
